//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cibertec_Examen_Final.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cibertec_Examen_Final.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AuthorID.
        /// </summary>
        public static string Auhor_au_id {
            get {
                return ResourceManager.GetString("Auhor_au_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string Author_au_city {
            get {
                return ResourceManager.GetString("Author_au_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FirstName.
        /// </summary>
        public static string Author_au_fname {
            get {
                return ResourceManager.GetString("Author_au_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LName.
        /// </summary>
        public static string Author_au_lname {
            get {
                return ResourceManager.GetString("Author_au_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Author_au_phone {
            get {
                return ResourceManager.GetString("Author_au_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salary.
        /// </summary>
        public static string Author_au_salary {
            get {
                return ResourceManager.GetString("Author_au_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sex.
        /// </summary>
        public static string Author_au_sex {
            get {
                return ResourceManager.GetString("Author_au_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string Author_au_state {
            get {
                return ResourceManager.GetString("Author_au_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        public static string Author_au_subject {
            get {
                return ResourceManager.GetString("Author_au_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZIP.
        /// </summary>
        public static string Author_au_zip {
            get {
                return ResourceManager.GetString("Author_au_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Book Advance.
        /// </summary>
        public static string Books_advance {
            get {
                return ResourceManager.GetString("Books_advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Book Note.
        /// </summary>
        public static string Books_notes {
            get {
                return ResourceManager.GetString("Books_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price Book.
        /// </summary>
        public static string Books_price {
            get {
                return ResourceManager.GetString("Books_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Book PubId.
        /// </summary>
        public static string Books_pub_id {
            get {
                return ResourceManager.GetString("Books_pub_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Book Pub Date.
        /// </summary>
        public static string Books_pubdate {
            get {
                return ResourceManager.GetString("Books_pubdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title Book.
        /// </summary>
        public static string Books_title {
            get {
                return ResourceManager.GetString("Books_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title_ID.
        /// </summary>
        public static string Books_title_id {
            get {
                return ResourceManager.GetString("Books_title_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type Book.
        /// </summary>
        public static string Books_type {
            get {
                return ResourceManager.GetString("Books_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Book ytd_sales.
        /// </summary>
        public static string Books_ytd_sales {
            get {
                return ResourceManager.GetString("Books_ytd_sales", resourceCulture);
            }
        }
    }
}
